services:
  web:
    build: .
    container_name: easy-finance
    ports:
      # Port mapping: <host_port>:<container_port>
      - "5000:8000"
    volumes:
      - finance_data:/app/instance
    environment:
      - FLASK_APP=app
    command: gunicorn --bind 0.0.0.0:8000 app:app

volumes:
  finance_data: